#!/bin/bash

in=${1:-""}
out=${2:-""}
pack=${2:-""}

source ~/.gdxtools

java -cp $GDXTOOLS/libgdx-tools/libgdx/gdx.jar:$GDXTOOLS/libgdx-tools/libgdx/extensions/gdx-tools/gdx-tools.jar com.badlogic.gdx.tools.texturepacker.TexturePacker $in $out $pack
